In [1]:
import numpy as np
import wandb

In [183]:
from rich import print
from rich import pretty
pretty.install()
from rich import inspect
from rich.console import Console
console = Console()
from rich.progress import track
from rich.columns import Columns

import os
import sys

In [2]:
wandb.init()

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Appending key for api.wandb.ai to your netrc file: /home/shiwen/.netrc


In [ ]:
if True : print("haha")

In [ ]:
def sum(*args):
    total = 0
    for i in args:
        total+=i
    print(total)

sum(1,2,3,4)
sum(*[1,2,3])

In [ ]:
def func(**kwargs):
    for k,v in kwargs.items():
        print(f'{k} is {v}')
dicA = {'a':1,'b':2}
func(a=1,b=2)
func(**dicA)

In [ ]:
from itertools import product
list(product(('A','B'), repeat=2))

In [184]:
print(None or 2)
print(2 or 3)

In [ ]:
for (i,j) in zip([1,2],[3,4]):
    print(i,j)

In [185]:
print((1, 2)[True])
print((1, 2)[False])
print((1, 2, 3)[True])

a=100
(a,50)[a>50]

50

In [186]:
ltestA = []
ltestA += [1,2]
ltestA += [3,4]

ltestB = []
ltestB.extend([1,2]) 
ltestB.extend([3,4]) 

ltestC = []
ltestC.append([1,2]) 
ltestC.append([3,4])
ltestA,ltestB,ltestC

([1, 2, 3, 4], [1, 2, 3, 4], [[1, 2], [3, 4]])

In [ ]:
a = [i*i for i in range(10) if i%2==0]
b = [i*i if i%2==0 else 'ha' for i in range(10)]
a,b

In [ ]:
a = [i for i in 'hello everybody' if i in 'aeiou']
b = {i for i in 'hello everybody' if i in 'aeiou'}
a,b

In [ ]:
b = (i*i if i%2==0 else 'ha' for i in range(10))
for i in b:
    print(i)

In [187]:
import string
{k:v for k,v in zip(string.ascii_lowercase[:5],range(5))}

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}

In [ ]:
[[i*j for j in range(4)] for i in range(3)]

In [ ]:
def addadd(n):
    i=0
    sum = 0
    while i < n:
        sum=sum+i
        i=i+1
        yield  sum
[i for i in addadd(10)]

In [ ]:
data = ['a','b','c']
{i:d for i,d in enumerate(data)}

In [188]:
x = [i**2 for i in range(1000)]
y = (i**2 for i in range(1000))

a = sum(x)
b = sum(y)
print(a,b)

import sys
sys.getsizeof(x),sys.getsizeof(y)

(9024, 88)

In [ ]:
from timeit import default_timer as timer

start = timer()
a = []
for i in range(1_000_000):
    a.append(i)
end = timer()
print(end - start)

start = timer()
a = [i for i in range(1_000_000)]
end = timer()
print(end - start)

In [ ]:
model_name = 'mobiledetnet-0.5'

expansion_t = float(model_name.split('nett')[1].split('-')[0]) if 'nett' in model_name else None
wide_factor = float(model_name.split('-')[1])

In [ ]:
wide_factor

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2],[3,4]])
np.expand_dims(a,axis=1).shape

In [ ]:
a=np.random.rand(3,2)
b=np.random.rand(4,2)
np.concatenate((a,b),axis=0)

In [ ]:
a=np.array([[1,1],[2,2]])
b=np.array([[1,2],[1,2]])
a,b

In [ ]:
a*b, a@b

In [ ]:
a = np.zeros((1,2))
b=a
b=b+2
a,b

In [ ]:
test='apple\dog'
set(test)

In [ ]:
a=np.arange(10)

In [ ]:
a=np.clip(a,3,5)

In [ ]:
a

In [ ]:
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
c=np.array([[0],[0],[0]])
a,b,c

In [ ]:
a+c,b+c

In [ ]:
a=[1,2,3]
a.append(4)
a

In [ ]:
len({1:a,2:b,3:c})

In [ ]:
{1:a,2:b,3:c}

In [ ]:
probs = np.array([0.1, 0.0, 0.7, 0.2])
idx = np.random.choice(range(len(probs)), p = probs)
idx

In [ ]:
# Python dictionaries and lists are "pass by reference"
dic={"a":1,"b":2}
def testfunc(dic):
    dic["a"]=3
testfunc(dic)
dic

In [ ]:
[2,3]*6

In [ ]:
[[2,3]]*6

In [ ]:
a=[]
a+[i for i in range(3)]+[3]

In [ ]:
a, b, c = 1,2,3
a,b,c

In [ ]:
[1,2,3,4][2:0:-1]

In [ ]:
model_name = 'mobiledetnetv2t2-1.0'
expansion_t = float(model_name.split('netv2t')[1].split(
    '-')[0]) if 'v2t' in model_name else None
wide_factor = float(model_name.split(
    '-')[1]) if '-' in model_name else 1.0

In [ ]:
expansion_t,wide_factor

In [ ]:
model_name.split('netv2t')

In [ ]:
assert 3 in [1,2]

In [ ]:
import math

init_channels = math.ceil(64 / 2)
new_channels = init_channels*(2-1)

init_channels, new_channels

In [ ]:
type(new_channels)

In [ ]:
30//4

In [ ]:
for i,(a,b,c,d,e) in enumerate(cfgs):
    print(i," ",a,b,c,d,e)

In [ ]:
import os
import shutil
import stat
import pathlib
import subprocess

In [ ]:
os.path.abspath()

In [ ]:
print(__file__)

In [ ]:
os.getcwd()

In [ ]:
os.path.realpath('__file__')

In [ ]:
os.chmod('test.py', 0o777)

In [ ]:
0o400

In [ ]:
os.listdir(os.getcwd())

In [ ]:
oct(os.stat("test.py").st_mode)

In [ ]:
shutil.copyfile('test.py', 'hellotest.py')

In [ ]:
os.path.abspath('switch.py')

In [ ]:
os.getcwd()

In [ ]:
subprocess.Popen('cmd.exe')

In [ ]:
exec('print(100)')

In [ ]:
a=[]
a.append(1)

In [ ]:
a

In [ ]:
nums = [1,2,3,4,5,6,7]

In [ ]:
nums.pop()

In [ ]:
nums.insert(0,nums.pop())
nums

In [ ]:
import pandas as pd
# this will run really really slow
table = pd.DataFrame(columns=['X','Y','new_X','new_Y'])
for i in range(10):
    table = table.append({'X':1,'Y':2,'new_X':3,'new_Y':4}, ignore_index=True)

# this will 10x↑ faster
table = {}
for i in range(10):
    table = table[len(table)] = {'X':1,'Y':2,'new_X':3,'new_Y':4}
preWarp_table = pd.DataFrame.from_dict(preWarp_table, "index")

In [ ]:
-3%10

In [ ]:
import sys
sys.int_info

In [ ]:
se = set()
se.add('s')
se

In [ ]:
import collections
s = "anagram"
s = collections.Counter(s)
s

In [ ]:
for i in range(ord('a'),ord('z')+1):
    print(chr(i))

In [ ]:
import string
string.ascii_lowercase[:14]

In [ ]:
"a0".isalnum()

In [ ]:
s= "mobiledetnett2-0.5"

In [ ]:
float(s.split('nett')[1].split('-')[0]) if 'nett' in s else None

In [ ]:
float(s.split('-')[1])

In [ ]:
s.split('nett')

In [ ]:
s='mobiledetnetv2t2'

In [ ]:
float(s.split('netv2t')[1].split('-')[0]) if 'v2t' in s else None

In [ ]:
# multi initial
a,b = (img,)*2

In [ ]:
locals()

In [ ]:
locals()

In [ ]:
inspect(list, methods=True)

In [ ]:
list

In [ ]:
console.print("Hello", "World!",style="strike")
console.print("Hello", "World!", style="bold red")
console.print("Where there is a [bold cyan]Will[/bold cyan] there [u]is[/u] a [i]way[/i].")

In [ ]:
test_data = [
    {"jsonrpc": "2.0", "method": "sum", "params": [None, 1, 2, 4, False, True], "id": "1",},
    {"jsonrpc": "2.0", "method": "notify_hello", "params": [7]},
    {"jsonrpc": "2.0", "method": "subtract", "params": [42, 23], "id": "2"},
]

def test_log():
    enabled = False
    context = {
        "foo": "bar",
    }
    movies = ["Deadpool", "Rise of the Skywalker"]
    console.log("Hello from", console, "!")
    console.log(test_data, log_locals=True)


test_log()

In [ ]:
def test():
    a=1
    b=[1,2,3]
    console.log("", log_locals=True)
test()

In [ ]:
console.print(":smiley: :vampire: :pile_of_poo: :thumbs_up: :raccoon:")

In [ ]:
import time
for step in track(range(100)):
    time.sleep(0.1)

In [ ]:
directory = os.listdir()
print(Columns(directory))

In [ ]:
inspect(list, methods=True)

In [ ]:
print("hello")

In [ ]:
def in_order(self):
    if self.left!=None:
        yield from self.left.in_order()
    yield self.root 
    if self.right!=None:
        yield from self.right.in_order()

In [ ]:
np.ones([3,4]) * 20

In [ ]:
initial_detection_points = np.array([2,4])
initial_detection_points

In [ ]:
initial_detection_points[np.newaxis, ...].shape[0]


In [ ]:
point = np.array([2,4])

In [ ]:
point.shape

In [ ]:
point = point[np.newaxis, ...]
point.shape

In [ ]:
num_points = point.shape[0]
num_points

In [ ]:
np.array([False] * 5)

In [ ]:
np.eye(4,2)

In [ ]:
point = np.array([[1,2],[3,4],[5,6]])
point

In [ ]:
point.shape

In [ ]:
ltest = [1,2,3]
def testest(lll):
    lll[0] += 1

In [ ]:
testest(ltest)

In [ ]:
ltest

In [ ]:
np.ones((2,3),dtype=np.int)

In [ ]:
np.expand_dims(point.flatten(),0).T

In [ ]:
from filterpy.kalman import KalmanFilter

In [ ]:
num_points = 3

In [ ]:
dim_x = 2 * 2 * num_points  # We need to accomodate for velocities
dim_z = 2 * num_points
dim_z = dim_z
filter = KalmanFilter(dim_x=dim_x, dim_z=dim_z)

In [ ]:
# State transition matrix (models physics): numpy.array()
filter.F = np.eye(dim_x)
dt = 1  # At each step we update pos with v * dt
for p in range(dim_z):
    filter.F[p, p + dim_z] = dt
filter.F

In [ ]:
# Measurement function: numpy.array(dim_z, dim_x)
filter.H = np.eye(
    dim_z,
    dim_x,
)

In [ ]:
# Measurement uncertainty (sensor noise): numpy.array(dim_z, dim_z)
# TODO: maybe we should open this one to the users, as it lets them
#       chose between giving more/less importance to the detections
filter.R *= 4.0

In [ ]:
# Process uncertainty: numpy.array(dim_x, dim_x)
# Don't decrease it too much or trackers pay too little attention to detections
# self.filter.Q[:dim_z, :dim_z] /= 50
filter.Q[dim_z:, dim_z:] /= 10

In [ ]:
# Initial state: numpy.array(dim_x, 1)
filter.x[:dim_z] = np.expand_dims(point.flatten(), 0).T

In [ ]:
# Estimation uncertainty: numpy.array(dim_x, dim_x)
filter.P[dim_z:, dim_z:] *= 10.0

In [ ]:
filter

In [ ]:
1<2<3<4

In [ ]:
strs = ["flower","flower","flower","flower"]

In [ ]:
for i in range(len(strs)):
    if len(strs[0]) > len(strs[i]):
        strs[0], strs[i] = strs[i], strs[0]

In [ ]:
strs

In [ ]:
for i in range(len(strs[0]),0,-1):
    if all(strs[0][:i] in str[:i] for str in strs[1:]):
        print(strs[0][:i])

In [ ]:
all('f' in i for i in strs[1:])

In [ ]:
long = strs[0]
for i in strs[1:]:
    while i.find(long)!=0

In [ ]:
'abc'.find('b')

In [ ]:
'abc'[:-1]

In [ ]:
a,*b, c = [1,2,3,4]
a,b,c

In [ ]:
[[] for _ in range(4)]

In [ ]:
{'a':1}.get('a',"Nope"),\
{'a':1}.get('b',"Nope")

In [ ]:
i = 0
while i < 5:
    i+=1
    # break
else:
    print("traversal hole loop")

In [190]:
distance_matrix = np.zeros((3,4))
distance_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [199]:
i = 0
for r,R in enumerate(distance_matrix):
    for c,_ in enumerate(R):
        distance_matrix[r,c] = i
        i += 1
distance_matrix[0,0] = 10
distance_matrix[1,2] = 0
distance_matrix

array([[10.,  1.,  2.,  3.],
       [ 4.,  5.,  0.,  7.],
       [ 8.,  9., 10., 11.]])

In [200]:
if distance_matrix.size > 0:
    det_idxs = []
    obj_idxs = []
    current_min = distance_matrix.min()
current_min

0.0

In [197]:
np.array([[5,4,3,6,7],[5,4,2,6,7]]).argmin()

7

In [209]:
flattened_arg_min = distance_matrix.argmin()
det_idx = flattened_arg_min // distance_matrix.shape[1]
obj_idx = flattened_arg_min % distance_matrix.shape[1]
det_idxs.append(det_idx)
obj_idxs.append(obj_idx)

distance_matrix[det_idx, :] = 30 + 1
distance_matrix[:, obj_idx] = 30 + 1

In [210]:
distance_matrix

array([[10.,  1., 31.,  3.],
       [31., 31., 31., 31.],
       [ 8.,  9., 31., 11.]])

In [216]:
np.zeros((2,3)).size

6

In [217]:
for i in range(10):
    input()
    print(i)

In [15]:
a = [np.array([1,2,3]),np.array([4,5,6])]

In [16]:
for i in a:
    i += 1
a

[array([2, 3, 4]), array([5, 6, 7])]

In [13]:
test

array([2, 3, 4])